---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluent-bit-plugin.otelCollectorName" . }}-shoot
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluent-bit-plugin.otelCollectorLabels" . | nindent 4 }}
data:
  otel-collector-config.yaml: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      file_storage: # Define the extension instance
        directory: /var/lib/otelcol/storage # Choose a persistent directory
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
        timeout: 5s
        send_batch_size: 10000
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 10
    exporters:
      debug:
        verbosity: basic
      otlphttp/logs:
        # Resilience https://opentelemetry.io/docs/collector/resiliency/
        sending_queue:
          storage: file_storage
          queue_size: 10000 # Increase queue size (default 1000)
        retry_on_failure:
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 10m # Increase m
        logs_endpoint: http://{{ include "fluent-bit-plugin.victorialogsName" . }}-shoot.{{ .Release.Namespace }}.svc.cluster.local:9428/insert/opentelemetry/v1/logs
        headers:
          VL-Stream-Fields: "k8s.event.reason,k8s.node.name,k8s.namespace.name,k8s.object.name,k8s.pods.name,k8s.container.name,severity,k8s.object.name,k8s.object.kind,origin"
    service:
      extensions: [health_check,file_storage]
      pipelines:
        logs:
          receivers: [otlp]
          processors: [memory_limiter,batch]
          exporters: [debug, otlphttp/logs]
      # Configure the collector own telemetry
      telemetry:
        # Emit collector logs to stdout
        logs:
          level: info
          encoding: console
          output_paths: [ stdout ]
          error_output_paths: [ stderr ]
        # Pull collector internal metrics to Prometheus
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: '0.0.0.0'
                    port: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fluent-bit-plugin.otelCollectorName" . }}-shoot
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluent-bit-plugin.otelCollectorLabels" . | nindent 4 }}
    app: {{ include "fluent-bit-plugin.otelCollectorName" . }}-shoot
spec:
  replicas: {{ .Values.otelCollector.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ include "fluent-bit-plugin.otelCollectorName" . }}-shoot
      {{- include "fluent-bit-plugin.otelCollectorSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "fluent-bit-plugin.otelCollectorName" . }}-shoot
        {{- include "fluent-bit-plugin.otelCollectorSelectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ .Values.otelCollector | toJson | sha256sum }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.otelCollector.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: otel-collector
          image: {{ .Values.otelCollector.image }}
          args:
            - --config=/conf/otel-collector-config.yaml
          {{- with .Values.otelCollector.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.otelCollector.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.otelCollector.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.otelCollector.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.otelCollector.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /conf
              readOnly: true
            - name: varlibotelcol
              mountPath: /var/lib/otelcol/storage
          {{- with .Values.otelCollector.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "fluent-bit-plugin.otelCollectorName" . }}-shoot
            defaultMode: 420
        - name:  varlibotelcol
          emptyDir: {}
      {{- with .Values.otelCollector.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.otelCollector.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.otelCollector.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        # Co-locate with victorialogs-shoot on the same node
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ include "fluent-bit-plugin.victorialogsName" . }}-shoot
                topologyKey: kubernetes.io/hostname
        # Avoid nodes with seed pods
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ include "fluent-bit-plugin.otelCollectorName" . }}-seed
                        - {{ include "fluent-bit-plugin.victorialogsName" . }}-seed
                topologyKey: kubernetes.io/hostname
      {{- with .Values.otelCollector.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluent-bit-plugin.otelCollectorName" . }}-shoot
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluent-bit-plugin.otelCollectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: otlp-grpc
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: otlp-http
      port: 4318
      protocol: TCP
      targetPort: 4318
    - name: metrics
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    {{- include "fluent-bit-plugin.otelCollectorSelectorLabels" . | nindent 4 }}
    app: {{ include "fluent-bit-plugin.otelCollectorName" . }}-shoot

